import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.io.File;
import java.util.ArrayList;

public class AplikasiResepFrame extends javax.swing.JFrame {

    // <-- BAGIAN INI HILANG (Variabel untuk Controller & JList Model)
    private ManajemenResep manajer;
    private DefaultListModel<Resep> listModel;

    /**
     * Creates new form AplikasiResepFrame
     */
    public AplikasiResepFrame() {
        initComponents();
        
        // <-- BAGIAN INI HILANG (Logika Inisialisasi Kustom)
        // 1. Buat Manajer (Controller)
        manajer = new ManajemenResep();
        
        // 2. Siapkan model untuk JList
        listModel = new DefaultListModel<>();
        jListResep.setModel(listModel); // Hubungkan listModel ke jListResep
        
        // 3. Matikan tombol Update/Hapus (UX yang baik)
        btnUpdate.setEnabled(false);
        btnHapus.setEnabled(false);

        // 4. Tambahkan EVENT LISTENER untuk JList
        // Ini akan "mendengar" setiap kali kita mengklik item di daftar
        jListResep.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    // Panggil method helper kita
                    jListResepValueChanged();
                }
            }
        });
        
        // 5. Atur Window di tengah layar
        this.setLocationRelativeTo(null);
    }
    
    // <-- SEMUA METHOD HELPER DI BAWAH INI HILANG -->
    
    /**
     * Dipanggil saat item di JList diklik.
     * Tugas: Ambil data resep yg diklik, tampilkan di field kanan.
     */
    private void jListResepValueChanged() {
        int selectedIndex = jListResep.getSelectedIndex();
        
        if (selectedIndex != -1) { // Jika ada item yg dipilih
            Resep resepTerpilih = listModel.getElementAt(selectedIndex);
            
            // Masukkan datanya ke text field
            txtJudul.setText(resepTerpilih.getJudul());
            areaBahan.setText(resepTerpilih.getBahan());
            areaInstruksi.setText(resepTerpilih.getInstruksi());
            
            // Aktifkan tombol Update & Hapus
            btnUpdate.setEnabled(true);
            btnHapus.setEnabled(true);
        } else {
            // Jika tidak ada yg dipilih (misal setelah hapus)
            btnUpdate.setEnabled(false);
            btnHapus.setEnabled(false);
        }
    }
    
    /**
     * Tugas: Mengosongkan semua field input.
     */
    private void clearFields() {
        txtJudul.setText("");
        areaBahan.setText("");
        areaInstruksi.setText("");
        jListResep.clearSelection(); // Hapus seleksi di JList
    }

    /**
     * Tugas: Sinkronkan JList dengan data terbaru dari 'Manajer'.
     */
    private void updateList() {
        listModel.clear(); // 1. Kosongkan JList
        
        // 2. Minta data terbaru ke Manajer
        ArrayList<Resep> daftar = manajer.getDaftarResep();
        
        // 3. Isi JList dengan data baru
        for (Resep r : daftar) {
            listModel.addElement(r);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListResep = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaBahan = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaInstruksi = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnImpor = new javax.swing.JButton();
        btnEkspor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Resep Masakan");

        jScrollPane1.setViewportView(jListResep);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Judul Resep:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Bahan-bahan:");

        areaBahan.setColumns(20);
        areaBahan.setRows(5);
        jScrollPane2.setViewportView(areaBahan);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Instruksi:");

        areaInstruksi.setColumns(20);
        areaInstruksi.setRows(5);
        jScrollPane3.setViewportView(areaInstruksi);

        btnTambah.setText("Tambah Resep Baru");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Resep Terpilih");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Resep Terpilih");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnImpor.setText("Impor ");
        btnImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImporActionPerformed(evt);
            }
        });

        btnEkspor.setText("Ekspor ");
        btnEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Daftar Resep");

        btnClear.setText("Clear Form");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus))
                    .addComponent(txtJudul)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImpor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEkspor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUpdate)
                            .addComponent(btnHapus))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnImpor)
                            .addComponent(btnEkspor)))
                    .addComponent(jScrollPane1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String judul = txtJudul.getText();
        String bahan = areaBahan.getText();
        String instruksi = areaInstruksi.getText();
        
        if (judul.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Judul resep tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Resep resepBaru = new Resep(judul, bahan, instruksi);
        manajer.tambahResep(resepBaru);
        
        updateList(); 
        clearFields(); 
        JOptionPane.showMessageDialog(this, "Resep '" + judul + "' berhasil ditambahkan!");
    }
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int selectedIndex = jListResep.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Pilih resep yang ingin di-update!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String judul = txtJudul.getText();
        String bahan = areaBahan.getText();
        String instruksi = areaInstruksi.getText();
        
        Resep resepUpdate = new Resep(judul, bahan, instruksi);
        manajer.updateResep(selectedIndex, resepUpdate);
        
        updateList();
        jListResep.setSelectedIndex(selectedIndex); 
        JOptionPane.showMessageDialog(this, "Resep '" + judul + "' berhasil diperbarui!");
    }
    
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int selectedIndex = jListResep.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Pilih resep yang ingin dihapus!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Resep resep = listModel.getElementAt(selectedIndex);
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Anda yakin ingin menghapus resep '" + resep.getJudul() + "'?",
                "Konfirmasi Hapus", 
                JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            manajer.hapusResep(selectedIndex);
            updateList();
            clearFields();
            JOptionPane.showMessageDialog(this, "Resep berhasil dihapus!");
        }
    }
    
    private void btnImporActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Buka File JSON");

        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();
            
            if (manajer.imporDariJSON(fileToOpen)) {
                updateList(); 
                clearFields();
                JOptionPane.showMessageDialog(this, "Data berhasil diimpor dari " + fileToOpen.getAbsolutePath());
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengimpor data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void btnEksporActionPerformed(java.awt.event.ActionEvent evt) {                                          
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan sebagai File JSON");
        fileChooser.setSelectedFile(new File("resep-saya.json")); 

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            
            if (manajer.eksporKeJSON(fileToSave)) {
                JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke " + fileToSave.getAbsolutePath());
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengekspor data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        clearFields();
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // <-- BAGIAN INI SAYA UBAH SEDIKIT AGAR LEBIH SIMPLE & MODERN
            // Menggunakan System Look and Feel (tampilan Windows/macOS)
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiResepFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiResepFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiResepFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiResepFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiResepFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaBahan;
    private javax.swing.JTextArea areaInstruksi;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEkspor;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImpor;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<Resep> jListResep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtJudul;
    // End of variables declaration//GEN-END:variables
}
